#!/usr/bin/env python3
"""Print the bootstrap.ipni.io DNS records as a Cloudflare-importable BIND file.

Generated from the inventory (IPs) and host_vars/<box>/bootstrap.yml (PeerIDs),
so the records can never drift from what is deployed:

  ./scripts/bootstrap-dns.py > dns.txt

Boxes without a bootstrap_peer_id are skipped (and reported on stderr).
"""
import os
import sys

import yaml

ZONE = "ipni.io"
NAME = f"bootstrap.{ZONE}"
PORT = 4001
WSS_PORT = 4443   # browsers: TLS via Envoy, see k8s/bootstrap-wss
TTL = 1   # "Auto" in Cloudflare, as in its own exports

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
hosts = yaml.safe_load(open(os.path.join(root, "inventory/hosts.yml")))["all"]["children"]["ipfs_nodes"]["hosts"]

boxes = []
for box, vars_ in hosts.items():
    path = os.path.join(root, "host_vars", box, "bootstrap.yml")
    if not os.path.exists(path):
        print(f"skipping {box}: no {path}", file=sys.stderr)
        continue
    boxes.append((box, vars_["ansible_host"], yaml.safe_load(open(path))["bootstrap_peer_id"]))

tag = "; cf_tags=cf-proxied:false"
out = [
    f";; Cloudflare DNS import for the {ZONE} bootstrap nodes (BIND format).",
    ";; GENERATED by scripts/bootstrap-dns.py - do not edit by hand.",
    ";; Import: DNS > Records > Import and Export > Import DNS records.",
    ";; Leave 'Proxy imported DNS records' UNCHECKED: raw libp2p TCP/UDP cannot",
    ";; be proxied. Every record also carries cf-proxied:false.",
    ";;",
    f";; Clients bootstrap with /dnsaddr/{NAME}/p2p/<PeerID>, one per box:",
    *[f";;   {box}  {pid}" for box, _, pid in boxes],
    "",
    ";; A records (DNS only)",
    *[f"{box}.{NAME}.\t{TTL}\tIN\tA\t{ip} {tag}" for box, ip, _ in boxes],
    "",
    ";; Shared name: one entry per bootstrap node",
    *[f'_dnsaddr.{NAME}.\t{TTL}\tIN\tTXT\t"dnsaddr=/dnsaddr/{box}.{NAME}/p2p/{pid}" {tag}' for box, _, pid in boxes],
]
for box, _, pid in boxes:
    out += ["", f";; {box}: its addresses (TCP, QUIC, and WSS for browsers)"]
    for proto in (f"tcp/{PORT}", f"udp/{PORT}/quic-v1", f"tcp/{WSS_PORT}/wss"):
        out.append(f'_dnsaddr.{box}.{NAME}.\t{TTL}\tIN\tTXT\t"dnsaddr=/dns4/{box}.{NAME}/{proto}/p2p/{pid}" {tag}')
print("\n".join(out))
